package um.tf2025.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static um.tf2025.domain.AssertUtils.bigDecimalCompareTo;
import static um.tf2025.domain.AssertUtils.zonedDataTimeSameInstant;

public class EventoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoAllPropertiesEquals(Evento expected, Evento actual) {
        assertEventoAutoGeneratedPropertiesEquals(expected, actual);
        assertEventoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoAllUpdatablePropertiesEquals(Evento expected, Evento actual) {
        assertEventoUpdatableFieldsEquals(expected, actual);
        assertEventoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoAutoGeneratedPropertiesEquals(Evento expected, Evento actual) {
        assertThat(actual)
            .as("Verify Evento auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoUpdatableFieldsEquals(Evento expected, Evento actual) {
        assertThat(actual)
            .as("Verify Evento relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a ->
                assertThat(a.getFechaZoned())
                    .as("check fechaZoned")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaZoned())
            )
            .satisfies(a ->
                assertThat(a.getPrecioBase())
                    .as("check precioBase")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioBase())
            )
            .satisfies(a -> assertThat(a.getStock()).as("check stock").isEqualTo(expected.getStock()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventoUpdatableRelationshipsEquals(Evento expected, Evento actual) {
        // empty method
    }
}
