package um.tf2025.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static um.tf2025.domain.AssertUtils.bigDecimalCompareTo;
import static um.tf2025.domain.AssertUtils.zonedDataTimeSameInstant;

public class VentaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAllPropertiesEquals(Venta expected, Venta actual) {
        assertVentaAutoGeneratedPropertiesEquals(expected, actual);
        assertVentaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAllUpdatablePropertiesEquals(Venta expected, Venta actual) {
        assertVentaUpdatableFieldsEquals(expected, actual);
        assertVentaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaAutoGeneratedPropertiesEquals(Venta expected, Venta actual) {
        assertThat(actual)
            .as("Verify Venta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaUpdatableFieldsEquals(Venta expected, Venta actual) {
        assertThat(actual)
            .as("Verify Venta relevant properties")
            .satisfies(a -> assertThat(a.getCantidad()).as("check cantidad").isEqualTo(expected.getCantidad()))
            .satisfies(a ->
                assertThat(a.getPrecioUnitario())
                    .as("check precioUnitario")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPrecioUnitario())
            )
            .satisfies(a -> assertThat(a.getTotal()).as("check total").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotal()))
            .satisfies(a ->
                assertThat(a.getFechaZoned())
                    .as("check fechaZoned")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getFechaZoned())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVentaUpdatableRelationshipsEquals(Venta expected, Venta actual) {
        assertThat(actual)
            .as("Verify Venta relationships")
            .satisfies(a -> assertThat(a.getEvento()).as("check evento").isEqualTo(expected.getEvento()));
    }
}
